"""
Documentation Generator Module - KIRA AI Operating System (Phase 10)
Generates READMEs, API documentation, architecture specifications,
Mermaid diagrams, setup guides, and changelogs.
"""

import os
import json
from typing import Dict, Any, List, Optional
from utils.logger import logger
from router.model_router import model_router


class DocGenerator:
    def __init__(self, workspace_root: str = "."):
        self.workspace_root = os.path.abspath(workspace_root)

    async def generate_readme(self, project_name: str = "KIRA AI OS Project") -> Dict[str, Any]:
        """Generates a professional Markdown README.md for the project."""
        readme_content = f"""# {project_name}

> Generated by **KIRA AI Operating System • Phase 10 Developer Intelligence Engine**

## 🚀 Overview

**{project_name}** is a state-of-the-art software application built with clean architecture, robust testing, containerization, and modern developer tooling.

## 🛠 Tech Stack

- **Primary Languages**: TypeScript, Python 3.12, React 19, Tailwind CSS
- **Frameworks**: Express, Vite, FastAPI
- **AI Engine**: Gemini 3.1 Flash / Live API, Grok 4 Model Router
- **DevOps**: Docker, Git, GitHub Actions, VS Code Workspace

## 📁 Architecture Diagram

```mermaid
graph TD
    UI[React / Vite Desktop Frontend] --> Express[Node Express Server :3000]
    UI --> LiveWS[Gemini Live Audio WebSocket]
    Express --> FastAPI[FastAPI Backend Engine :8000]
    FastAPI --> DevEngine[Phase 10 Developer Intelligence]
    FastAPI --> ModelRouter[Phase 12 AI Model Router]
    FastAPI --> MemoryEngine[Phase 5 Vector / SQLite Memory]
```

## 🔧 Installation & Setup

1. **Clone repository**:
   ```bash
   git clone https://github.com/user/{project_name.lower().replace(' ', '-')}.git
   cd {project_name.lower().replace(' ', '-')}
   ```

2. **Install Node & Python Dependencies**:
   ```bash
   npm install
   pip install -r requirements.txt
   ```

3. **Set Environment Variables**:
   ```bash
   cp .env.example .env
   # Add your GEMINI_API_KEY
   ```

4. **Launch Application**:
   ```bash
   npm run dev
   ```

## 🧪 Running Tests

```bash
# Run Python backend tests
pytest -v

# Run frontend build verification
npm run build
```

## 📄 License

MIT License © 2026 KIRA AI
"""
        dest = os.path.join(self.workspace_root, "README.md")
        with open(dest, 'w', encoding='utf-8') as f:
            f.write(readme_content)

        return {
            "status": "success",
            "file": "README.md",
            "content": readme_content
        }

    async def generate_changelog(self) -> Dict[str, Any]:
        """Generates a CHANGELOG.md based on project milestones."""
        changelog = """# Changelog

All notable changes to this project will be documented in this file.

## [1.0.0] - Phase 10 Developer Intelligence Release

### Added
- **Developer Intelligence Engine**: Code analysis, AI code generator, debugger, unit & Playwright testing.
- **Multi-Language Support**: Python, JS, TS, React, Next.js, C++, Java, Go, Rust, PHP, SQL, Shell, PowerShell.
- **Git & GitHub Integration**: Automated commit generation, pull requests, issue tracking, and branch merging.
- **Docker & Containerization**: Automated Dockerfile and docker-compose generation with log diagnosis.
- **VS Code API Workspace**: Symbol navigation, project search, and launch/tasks.json generation.
- **Security Scanner**: Secret detection, dependency security vulnerability scanner.
- **AI Pair Programming Canvas**: Refactoring, design pattern suggestions, and code explanation.
"""
        dest = os.path.join(self.workspace_root, "CHANGELOG.md")
        with open(dest, 'w', encoding='utf-8') as f:
            f.write(changelog)

        return {
            "status": "success",
            "file": "CHANGELOG.md",
            "content": changelog
        }


doc_generator = DocGenerator()
